sudo: false
language: node_js
node_js:
  - "8"
cache:
  directory:
    - "node_modules"
script:
  npm run lint
  npm run test
deploy:
  provider: heroku
  api_key: ""
  app:
    master: shri-suggester
