sudo: false
language: node_js
node_js:
- '8'
cache:
  directory:
  - node_modules
script:
  - npm run lint
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: ecOvDKKo57i0Do9eJ0k1US0aQzImpgO0fwKiXeVjkWggAZoXtZYYHE2HEzb2hRN++ReByS3f244OsTJK4lYcM7pQ1LZGUXM7OjCau8NyRQhkdkbfT7GyfjrHYQMuRA7T80uUKkTm+1KuGE8HY4UqpmgffBNto1OTPO+V4YlM3/xrDhPcPeUnZKPNH0y7+TAik+tPzAU0ny8mmjCmkZKpBIZjhJ8XUFJ6OnaFHxeATaHAavxOo9r+Wm40zuA9KQGBnOSQTsklvclGsmkGvNpb+qZf8cMv6IjLsKjOZYCNuOU4MruMYarzaJ4KXHBxSdYwm9/GWdlBxRyBnixaKCTGS7xy5tZSR/+e0l56g3w596YaXN5Lfbg6/ahRLKlIZzauRTTfTVTbtiFNliiNkL5V0YZwGSHs/1hA83PAyZzHmz3pqTzQghcfQp9O5Pg2RvWzDqcc5F2JPL9dsmiv4Yf6Oys1SxDMnbBxaPFKUz+I3JlwsypD2wFBIIKC3ZSiSloKwtdVeJkUYc9y0wDkwKoG+VLxcZbrB8/2bkUOwkTckHiL35pj/gAF1WRpnGjwIgL6QoARVFnyyDYsfQBA8u5SMQA0XCG0MAPhQ9nBCjNeB3WM5jeEhAp60kc0tFwXdvsdzyyCuewb4BAM/pUed84gR0sNwtQ6x4P37C+eiTkVNmw=
  app:
    master: shri-suggester
  run:
    - npm run server
